---
AWSTemplateFormatVersion: 2010-09-09
Description: "Table Stack"
Resources:
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: "person_id"
        AttributeType: "N"
      - AttributeName: "sort_key"
        AttributeType: "S"
      KeySchema:
      - AttributeName: "person_id"
        KeyType: "HASH"
      - AttributeName: "sort_key"
        KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 100
        WriteCapacityUnits: 1000
              
Outputs:
  TableName:
    Description: DDB Table  
    Value: !Ref Table