usage:
	@echo "run with a command"

vpc-up:
	./vpc-up.sh

vpc-down: 
	./vpc-down.sh

pipe-up:
	./pipe_up.sh
	
pipe-down:
	./pipe_down.sh
	
stack-up:
	./stack_up.sh
	
stack-down:
	./stack_down.sh

stack-run:
	./stack_run.sh

end-up:
	./endpoint_up.sh
	./endpoint_push.sh

end-down:
	./endpoint_down.sh

end-ssh:
	./endpoint_ssh.sh

zeppelin: end-up
	./zeppelin_build.sh
	./zeppelin_up.sh
